version: '3.5'

services:

  web:
    environment:
      SERVICE_PUBLISH: "/kursutveckling"
      SERVER_HOST_URL: "https://www-r-new.referens.sys.kth.se/"
      SERVER_PORT: 3000
      KURSUTVECKLING_API_URI: 'https://api-r.referens.sys.kth.se/api/kursutveckling?defaultTimeout=10000'
      CAS_SSO_URI: 'https://login-r.referens.sys.kth.se'
      CM_HOST_URL: 'https://www-r.referens.sys.kth.se/cm/'
      KOPPS_URI: 'https://kopps-r.referens.sys.kth.se/api/kopps/v2/?defaultTimeout=60000'
      KURSPLAN_API_URI: 'https://api-r.referens.sys.kth.se/api/kursplan?defaultTimeout=60000'


      SESSION_USE_REDIS: 'true'


    env_file:
      - .env

    build: .

    ports:
      - 3000
